version: '2'
services:
  web:
    build: .
    command: web
    ports:
      - "8000:8000"
    links:
      - redis
      - db
      - search
  worker:
    build: .
    command: worker
    links:
      - redis
      - db
      - search
  redis:
    image: redis
  db:
    image: postgres
  search:
    image: elasticsearch